/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed2;
  GtkWidget *label43;
  GtkWidget *fixed3;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label6;
  GtkWidget *entry4;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *hbox11;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *comboboxentry1;
  GtkWidget *comboboxentry2;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton2;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label11;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *fixed4;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *label17;
  GtkWidget *entry8;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *hbox12;
  GtkWidget *radiobutton7;
  GSList *radiobutton7_group = NULL;
  GtkWidget *radiobutton8;
  GtkWidget *label16;
  GtkWidget *label19;
  GtkWidget *label18;
  GtkWidget *label24;
  GtkWidget *comboboxentry9;
  GtkWidget *comboboxentry4;
  GtkWidget *label44;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton4;
  GtkWidget *button4;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *label31;
  GtkWidget *entry9;
  GtkWidget *button5;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label28;
  GtkWidget *button7;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label30;
  GtkWidget *label32;
  GtkWidget *fixed6;
  GtkWidget *treeview2;
  GtkWidget *button12;
  GtkWidget *button9;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label36;
  GtkWidget *label33;
  GtkWidget *entry10;
  GtkWidget *label34;
  GtkWidget *button8;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label35;
  GtkWidget *label38;
  GtkWidget *fixed7;
  GtkWidget *treeview3;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *buttonaffecter;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label41;
  GtkWidget *button13;
  GtkWidget *alignment11;
  GtkWidget *hbox13;
  GtkWidget *image11;
  GtkWidget *label46;
  GtkWidget *label40;
  GtkWidget *label39;
  GtkWidget *button14;
  GtkWidget *alignment12;
  GtkWidget *hbox14;
  GtkWidget *image12;
  GtkWidget *label47;
  GtkWidget *label45;
  GtkWidget *label42;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_container_add (GTK_CONTAINER (window2), notebook1);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed2);

  label43 = gtk_label_new (_("label43"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed2), label43, 640, 56);
  gtk_widget_set_size_request (label43, 216, 48);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_fixed_put (GTK_FIXED (fixed2), fixed3, 0, 0);
  gtk_widget_set_size_request (fixed3, 0, 0);

  spinbutton1_adj = gtk_adjustment_new (1, 0, 400, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton1, 120, 176);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label1 = gtk_label_new (_("pricing"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed3), label1, 16, 376);
  gtk_widget_set_size_request (label1, 72, 40);

  label2 = gtk_label_new (_("type of parking"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed3), label2, 0, 248);
  gtk_widget_set_size_request (label2, 128, 48);

  label3 = gtk_label_new (_("name parking"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 16, 64);
  gtk_widget_set_size_request (label3, 96, 32);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed3), entry1, 128, 16);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry2, 120, 64);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed3), entry3, 128, 120);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  label4 = gtk_label_new (_("id parking"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 16, 16);
  gtk_widget_set_size_request (label4, 80, 32);

  label5 = gtk_label_new (_("location"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 16, 120);
  gtk_widget_set_size_request (label5, 104, 32);

  label6 = gtk_label_new (_("capacity"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed3), label6, 16, 176);
  gtk_widget_set_size_request (label6, 88, 32);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed3), entry4, 480, 16);
  gtk_widget_set_size_request (entry4, 160, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  label7 = gtk_label_new (_("opening time of "));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed3), label7, 0, 512);
  gtk_widget_set_size_request (label7, 152, 32);

  label8 = gtk_label_new (_("H"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed3), label8, 136, 512);
  gtk_widget_set_size_request (label8, 152, 32);

  label9 = gtk_label_new (_("min"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed3), label9, 304, 520);
  gtk_widget_set_size_request (label9, 49, 17);

  label10 = gtk_label_new (_("remarques"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 384, 24);
  gtk_widget_set_size_request (label10, 81, 32);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_fixed_put (GTK_FIXED (fixed3), hbox11, 144, 272);
  gtk_widget_set_size_request (hbox11, 32, 16);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("private"));
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox11), radiobutton2, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("public"));
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (hbox11), radiobutton1, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry1, 136, 520);
  gtk_widget_set_size_request (comboboxentry1, 61, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("20"));

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed3), comboboxentry2, 232, 520);
  gtk_widget_set_size_request (comboboxentry2, 61, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("31"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("32"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("33"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("34"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("35"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("36"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("37"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("38"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("39"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("41"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("42"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("43"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("44"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("46"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("47"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("48"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("49"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("50"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("51"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("52"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("53"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("54"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("56"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("57"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("58"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("59"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), "");

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("hourly rate "));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 120, 352);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("daily rate"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton3, 120, 392);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("monthly rate"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton2, 120, 440);
  gtk_widget_set_size_request (checkbutton2, 118, 24);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed3), button1, 520, 96);
  gtk_widget_set_size_request (button1, 66, 29);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("add"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox1), label11, FALSE, FALSE, 0);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 592, 96);
  gtk_widget_set_size_request (button2, 80, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("refresh"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox2), label12, FALSE, FALSE, 0);

  label13 = gtk_label_new (_("ADD"));
  gtk_widget_show (label13);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label13);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 500, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 120, 176);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  label14 = gtk_label_new (_("pricing"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed4), label14, 16, 376);
  gtk_widget_set_size_request (label14, 72, 40);

  label15 = gtk_label_new (_("type of parking"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 0, 248);
  gtk_widget_set_size_request (label15, 128, 48);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 128, 16);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 128, 72);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 128, 120);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  label17 = gtk_label_new (_("id parking"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 16, 16);
  gtk_widget_set_size_request (label17, 80, 32);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 480, 16);
  gtk_widget_set_size_request (entry8, 160, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label20 = gtk_label_new (_("opening time of "));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 0, 512);
  gtk_widget_set_size_request (label20, 152, 32);

  label21 = gtk_label_new (_("H"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 136, 512);
  gtk_widget_set_size_request (label21, 152, 32);

  label22 = gtk_label_new (_("min"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 304, 520);
  gtk_widget_set_size_request (label22, 49, 17);

  label23 = gtk_label_new (_("remarques"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 384, 24);
  gtk_widget_set_size_request (label23, 81, 32);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox12);
  gtk_fixed_put (GTK_FIXED (fixed4), hbox12, 160, 272);
  gtk_widget_set_size_request (hbox12, 32, 16);

  radiobutton7 = gtk_radio_button_new_with_mnemonic (NULL, _("public"));
  gtk_widget_show (radiobutton7);
  gtk_box_pack_start (GTK_BOX (hbox12), radiobutton7, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton7), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton7));

  radiobutton8 = gtk_radio_button_new_with_mnemonic (NULL, _("private"));
  gtk_widget_show (radiobutton8);
  gtk_box_pack_start (GTK_BOX (hbox12), radiobutton8, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton8), radiobutton7_group);
  radiobutton7_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton8));

  label16 = gtk_label_new (_("name parking"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 16, 64);
  gtk_widget_set_size_request (label16, 96, 32);

  label19 = gtk_label_new (_("capacity"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 16, 176);
  gtk_widget_set_size_request (label19, 88, 32);

  label18 = gtk_label_new (_("location"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 16, 120);
  gtk_widget_set_size_request (label18, 104, 32);

  label24 = gtk_label_new (_("fail"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 720, 56);
  gtk_widget_set_size_request (label24, 65, 16);

  comboboxentry9 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry9);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry9, 136, 520);
  gtk_widget_set_size_request (comboboxentry9, 61, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry9), _("20"));

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed4), comboboxentry4, 232, 520);
  gtk_widget_set_size_request (comboboxentry4, 61, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("31"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("32"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("33"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("34"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("35"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("36"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("37"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("38"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("39"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("41"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("42"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("43"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("44"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("46"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("47"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("48"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("49"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("50"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("51"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("52"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("53"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("54"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("56"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("57"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("58"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry4), _("59"));

  label44 = gtk_label_new (_("label44"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 584, 120);
  gtk_widget_set_size_request (label44, 224, 24);

  checkbutton5 = gtk_check_button_new_with_mnemonic (_("monthly rate"));
  gtk_widget_show (checkbutton5);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton5, 120, 440);
  gtk_widget_set_size_request (checkbutton5, 118, 24);

  checkbutton6 = gtk_check_button_new_with_mnemonic (_("daily rate"));
  gtk_widget_show (checkbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton6, 120, 392);
  gtk_widget_set_size_request (checkbutton6, 118, 24);

  checkbutton4 = gtk_check_button_new_with_mnemonic (_("hourly rate "));
  gtk_widget_show (checkbutton4);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton4, 120, 352);
  gtk_widget_set_size_request (checkbutton4, 118, 24);

  button4 = gtk_button_new_with_mnemonic (_("modify "));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed4), button4, 608, 88);
  gtk_widget_set_size_request (button4, 66, 29);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 704, 16);
  gtk_widget_set_size_request (button3, 80, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("search"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox3), label25, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("modify"));
  gtk_widget_show (label26);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label26);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 8, 136);
  gtk_widget_set_size_request (treeview1, 776, 224);

  label31 = gtk_label_new (_("id parking"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 144, 64);
  gtk_widget_set_size_request (label31, 97, 25);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 248, 64);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed5), button5, 416, 432);
  gtk_widget_set_size_request (button5, 66, 29);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button5), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("apply"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox4), label28, FALSE, FALSE, 0);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed5), button7, 496, 64);
  gtk_widget_set_size_request (button7, 96, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button7), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("search "));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, FALSE, FALSE, 0);

  label32 = gtk_label_new (_("show"));
  gtk_widget_show (label32);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label32);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 32, 176);
  gtk_widget_set_size_request (treeview2, 800, 168);

  button12 = gtk_button_new_with_mnemonic (_("refresh"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed6), button12, 568, 384);
  gtk_widget_set_size_request (button12, 74, 29);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_fixed_put (GTK_FIXED (fixed6), button9, 480, 384);
  gtk_widget_set_size_request (button9, 74, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button9), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("delete"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox8), label36, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("id parking"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 200, 64);
  gtk_widget_set_size_request (label33, 97, 25);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 336, 64);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  label34 = gtk_label_new (_("select a parking to delete "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 280, 136);
  gtk_widget_set_size_request (label34, 232, 16);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed6), button8, 552, 64);
  gtk_widget_set_size_request (button8, 120, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button8), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("search "));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox7), label35, FALSE, FALSE, 0);

  label38 = gtk_label_new (_("remove"));
  gtk_widget_show (label38);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label38);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview3, 32, 232);
  gtk_widget_set_size_request (treeview3, 832, 184);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed7), entry11, 560, 88);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed7), entry12, 560, 144);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  buttonaffecter = gtk_button_new ();
  gtk_widget_show (buttonaffecter);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonaffecter, 688, 456);
  gtk_widget_set_size_request (buttonaffecter, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonaffecter), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("assing"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox10), label41, FALSE, FALSE, 0);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed7), button13, 264, 88);
  gtk_widget_set_size_request (button13, 136, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button13), alignment11);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox13);

  image11 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox13), image11, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("search agent"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox13), label46, FALSE, FALSE, 0);

  label40 = gtk_label_new (_("id agent "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed7), label40, 424, 88);
  gtk_widget_set_size_request (label40, 89, 32);

  label39 = gtk_label_new (_("id parking"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed7), label39, 432, 144);
  gtk_widget_set_size_request (label39, 105, 24);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed7), button14, 272, 152);
  gtk_widget_set_size_request (button14, 136, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button14), alignment12);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox14);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox14), image12, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("search parking"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox14), label47, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("Message"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed7), label45, 240, 128);
  gtk_widget_set_size_request (label45, 184, 16);

  label42 = gtk_label_new (_("assign"));
  gtk_widget_show (label42);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label42);

  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3, "toggled",
                    G_CALLBACK (on_checkbutton3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton7, "toggled",
                    G_CALLBACK (on_radiobutton7_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton8, "toggled",
                    G_CALLBACK (on_radiobutton8_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5, "toggled",
                    G_CALLBACK (on_checkbutton5_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6, "toggled",
                    G_CALLBACK (on_checkbutton6_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4, "toggled",
                    G_CALLBACK (on_checkbutton4_toggled),
                    NULL);
  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaffecter, "clicked",
                    G_CALLBACK (on_buttonaffecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (window2, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window2, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, label43, "label43");
  GLADE_HOOKUP_OBJECT (window2, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window2, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window2, label1, "label1");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window2, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window2, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, label6, "label6");
  GLADE_HOOKUP_OBJECT (window2, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (window2, label7, "label7");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window2, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window2, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (window2, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (window2, checkbutton3, "checkbutton3");
  GLADE_HOOKUP_OBJECT (window2, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (window2, button1, "button1");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, image1, "image1");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, button2, "button2");
  GLADE_HOOKUP_OBJECT (window2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window2, image2, "image2");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window2, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (window2, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (window2, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, label22, "label22");
  GLADE_HOOKUP_OBJECT (window2, label23, "label23");
  GLADE_HOOKUP_OBJECT (window2, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window2, radiobutton7, "radiobutton7");
  GLADE_HOOKUP_OBJECT (window2, radiobutton8, "radiobutton8");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, label24, "label24");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry9, "comboboxentry9");
  GLADE_HOOKUP_OBJECT (window2, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (window2, label44, "label44");
  GLADE_HOOKUP_OBJECT (window2, checkbutton5, "checkbutton5");
  GLADE_HOOKUP_OBJECT (window2, checkbutton6, "checkbutton6");
  GLADE_HOOKUP_OBJECT (window2, checkbutton4, "checkbutton4");
  GLADE_HOOKUP_OBJECT (window2, button4, "button4");
  GLADE_HOOKUP_OBJECT (window2, button3, "button3");
  GLADE_HOOKUP_OBJECT (window2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window2, image3, "image3");
  GLADE_HOOKUP_OBJECT (window2, label25, "label25");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");
  GLADE_HOOKUP_OBJECT (window2, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window2, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window2, label31, "label31");
  GLADE_HOOKUP_OBJECT (window2, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (window2, button5, "button5");
  GLADE_HOOKUP_OBJECT (window2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window2, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2, label28, "label28");
  GLADE_HOOKUP_OBJECT (window2, button7, "button7");
  GLADE_HOOKUP_OBJECT (window2, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window2, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label30, "label30");
  GLADE_HOOKUP_OBJECT (window2, label32, "label32");
  GLADE_HOOKUP_OBJECT (window2, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (window2, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, button9, "button9");
  GLADE_HOOKUP_OBJECT (window2, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window2, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window2, image8, "image8");
  GLADE_HOOKUP_OBJECT (window2, label36, "label36");
  GLADE_HOOKUP_OBJECT (window2, label33, "label33");
  GLADE_HOOKUP_OBJECT (window2, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, button8, "button8");
  GLADE_HOOKUP_OBJECT (window2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, label38, "label38");
  GLADE_HOOKUP_OBJECT (window2, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window2, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (window2, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (window2, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (window2, buttonaffecter, "buttonaffecter");
  GLADE_HOOKUP_OBJECT (window2, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window2, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, label41, "label41");
  GLADE_HOOKUP_OBJECT (window2, button13, "button13");
  GLADE_HOOKUP_OBJECT (window2, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window2, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window2, image11, "image11");
  GLADE_HOOKUP_OBJECT (window2, label46, "label46");
  GLADE_HOOKUP_OBJECT (window2, label40, "label40");
  GLADE_HOOKUP_OBJECT (window2, label39, "label39");
  GLADE_HOOKUP_OBJECT (window2, button14, "button14");
  GLADE_HOOKUP_OBJECT (window2, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window2, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window2, image12, "image12");
  GLADE_HOOKUP_OBJECT (window2, label47, "label47");
  GLADE_HOOKUP_OBJECT (window2, label45, "label45");
  GLADE_HOOKUP_OBJECT (window2, label42, "label42");

  return window2;
}

